"""
test_playlist.py - Tests for YouTube playlist collection, credit parsing, and track ordering.
"""

from pathlib import Path
import tempfile
import yaml

from harmonic_resonance.groove.playlist import (
    slugify,
    format_duration,
    parse_youtube_description,
)
from harmonic_resonance.groove.context import GrooveContext, Scope
from harmonic_resonance.groove.cli import build_parser


def test_slugify():
    assert slugify("Too High") == "too-high"
    assert slugify("Don't You Worry 'Bout A Thing") == "dont-you-worry-bout-a-thing"
    assert slugify("He's Misstra Know-It-All") == "hes-misstra-know-it-all"
    assert slugify("Living for the City (1973)") == "living-for-the-city-1973"


def test_format_duration():
    assert format_duration(223) == "3:43"
    assert format_duration(276) == "4:36"
    assert format_duration(3665) == "1:01:05"
    assert format_duration(0) == "0:00"


def test_parse_youtube_description():
    sample_desc = """Provided to YouTube by Universal Music Group

Too High · Stevie Wonder

Innervisions

℗ 1973 UMG Recordings, Inc.

Released on: 1973-01-01

Recordingarranger, Producer, Composer Lyricist: Stevie Wonder
Engineer, Associate Producer: Malcolm Cecil
Associate Producer, Engineer: Robert Margouleff
Recording Engineer: Austin Godsey
Recording Engineer: Dan Barbiero

Auto-generated by YouTube."""

    parsed = parse_youtube_description(sample_desc)
    assert parsed["release_date"] == "1973-01-01"
    assert "1973 UMG Recordings" in parsed["copyright"]
    credits = parsed["credits"]
    assert "Stevie Wonder" in credits
    assert any("Producer" in r for r in credits["Stevie Wonder"])
    assert any("Recording Arranger" in r for r in credits["Stevie Wonder"])
    assert "Malcolm Cecil" in credits
    assert any("Engineer" in r for r in credits["Malcolm Cecil"])
    assert "Austin Godsey" in credits
    assert any("Recording Engineer" in r for r in credits["Austin Godsey"])


def test_list_songs_respects_album_track_order():
    with tempfile.TemporaryDirectory() as tmpdir:
        tracks_dir = Path(tmpdir)
        album_dir = tracks_dir / "stevie-wonder" / "test-album"
        album_dir.mkdir(parents=True)

        # Create 3 song directories named so alphabetical is C, B, A
        (album_dir / "zebra-song").mkdir()
        (album_dir / "alpha-song").mkdir()
        (album_dir / "middle-song").mkdir()

        # Define album.yaml with specific track order: zebra (1), middle (2), alpha (3)
        yaml_content = {
            "title": "Test Album",
            "artist": "Stevie Wonder",
            "tracks": [
                {"track_number": 1, "slug": "zebra-song", "title": "Zebra Song"},
                {"track_number": 2, "slug": "middle-song", "title": "Middle Song"},
                {"track_number": 3, "slug": "alpha-song", "title": "Alpha Song"},
            ]
        }
        with open(album_dir / "album.yaml", "w") as f:
            yaml.safe_dump(yaml_content, f)

        ctx = GrooveContext(
            scope=Scope.ALBUM,
            cwd=album_dir,
            tracks_dir=tracks_dir,
            artist="stevie-wonder",
            album="test-album",
        )

        songs = ctx.list_songs(artist="stevie-wonder", album="test-album")
        slugs = [s[2] for s in songs]
        assert slugs == ["zebra-song", "middle-song", "alpha-song"]


def test_cli_collect_playlist_subparser():
    parser = build_parser()
    args = parser.parse_args(["collect-playlist", "https://www.youtube.com/playlist?list=123", "--no-download"])
    assert args.command == "collect-playlist"
    assert args.url == "https://www.youtube.com/playlist?list=123"
    assert args.no_download is True
    assert args.format == "webm"
